spring:
  application:
    name: bank-spring-boot

  mvc:
    format:
      date: yyyy-MM-dd

  jpa:
    open-in-view: false

  threads:
    virtual:
      enabled: true

  profiles:
    active: ${PROFILE_ACTIVE}
server:
  port: 8080

app:
  jwt:
    issuer: bank-spring-boot
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7

bank:
  customer-types:
    INDIVIDUAL:
      max-transaction-limit: 50000000
    BUSINESS:
      max-transaction-limit: 500000000