spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    com.yourname.bank: INFO

app:
  jwt:
    secret: ${JWT_SECRET}

  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}